
version: '3'
services:
  licensingservice:
    image: ostock/licensing-service:0.0.1-SNAPSHOT
    environment:
      PROFILE: "dev"
      CONFIGSERVER_URI: http://localhost:8071
      CONFIGSERVER_PORT:   "8071"
    ports:
      - "8080:8080"
